# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-time

# >> macros
# << macros

Summary:    Wall clock plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-time
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-time.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(timed)
Provides:   nemo-qml-plugins-time > 0.3.15
Obsoletes:   nemo-qml-plugins-time <= 0.3.15

%description
%{summary}.

%package tests
Summary:    QML time plugin tests
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   nemo-qml-plugins-time-tests > 0.3.15
Obsoletes:   nemo-qml-plugins-time-tests <= 0.3.15

%description tests
Tests for QML time plugin


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/time/libnemotime.so
%{_libdir}/qt4/imports/org/nemomobile/time/qmldir
# >> files
# << files

%files tests
%defattr(-,root,root,-)
/opt/tests/nemo-qml-plugins/time/*
# >> files tests
# << files tests
